FROM mhart/alpine-node:8 AS build-env
MAINTAINER kai@blockchaintp.com
RUN apk update
RUN apk upgrade
RUN apk add bash git
WORKDIR /app/frontend
COPY ./package.json /app/frontend/package.json
COPY ./yarn.lock /app/frontend/yarn.lock
RUN yarn install
COPY ./ /app/frontend
RUN yarn run build

FROM nginx
MAINTAINER kai@blockchaintp.com
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build-env /app/frontend/dist /www
